version: "3.9"

services:
  app:
    build: .
    container_name: blog-api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog
      JWT_SECRET: dev-secret
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:16-alpine
    container_name: blog-db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Dev-only Postgres for running the app locally on host machine (no app container)
  db-dev:
    image: postgres:16-alpine
    profiles: ["dev"]
    container_name: blog-db-dev
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  db-dev-data:
